/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaAppClient;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patrick
 */
public class DetailRumah extends javax.swing.JFrame {

    Socket client;
    DataOutputStream out;
    BufferedReader inp;
    FormPilihan frm;
//String infoTambah ="";

    /**
     * Creates new form Konsultasi
     */
    public DetailRumah() {
        initComponents();
    }

    public DetailRumah(Socket s, DataOutputStream outs, BufferedReader inps) {
        try {
            initComponents();
            client = s;
            out = outs;
            inp = inps;
            System.out.println("41");
            out.writeBytes("daftar rumah\n");
            Refreshtable();
        } catch (IOException ex) {
            Logger.getLogger(DetailRumah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public DetailRumah(FormPilihan form, Socket s) {
        initComponents();
        try {
            frm = form;
            this.client = s;
            this.out = new DataOutputStream((client.getOutputStream()));
            this.inp = new BufferedReader(new InputStreamReader(client.getInputStream()));
            System.out.println("56");
            out.writeBytes("daftar rumah\n");

            Refreshtable();
        } catch (Exception ex) {
            Logger.getLogger(Reservasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProfil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setText("DETAIL RUMAH");

        tableProfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Rumah", "Alamat", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProfilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(lblJudul)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblJudul)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProfilMouseClicked
        // TODO add your handling code here:
        int i = tableProfil.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableProfil.getModel();

        String nama = model.getValueAt(i, 0).toString();
        String alamat = model.getValueAt(i, 1).toString();
        String harga = model.getValueAt(i, 2).toString();

        Konsultasi k = new Konsultasi(client, nama, alamat, harga, out, inp);
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tableProfilMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frm.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailRumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTable tableProfil;
    // End of variables declaration//GEN-END:variables

    // <editor-fold defaultstate="collapsed" desc="Refreshtable()">
    public void Refreshtable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tableProfil.getModel();
            model.setRowCount(0);
            Object[] rowData = new Object[3];
            System.out.println("197");
            String pesan = inp.readLine();

            String[] info = pesan.split("-");

            StringBuilder b = new StringBuilder(pesan);
            b.replace(pesan.lastIndexOf("-"), pesan.lastIndexOf("-") + 1, "");
            pesan = b.toString();

            for (int i = 0; i < info.length; i += 3) {
                rowData[0] = info[i];
                rowData[1] = info[1 + i];
                rowData[2] = info[2 + i];
                model.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(DetailRumah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // </editor-fold>
}
