/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaAppClient;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.net.Socket;

/**
 *
 * @author patrick
 */
public class FormDetailProperti extends javax.swing.JFrame {
    Socket client;
    int no=1;
    BufferedReader inp;
    DataOutputStream out;
    /**
     * Creates new form Konsultasi
     */
    public FormDetailProperti() {
        initComponents();
    }
 
    public FormDetailProperti(Socket s, String nama, String alamat, String kota, String harga, String tipe, DataOutputStream outs, BufferedReader inps) {
        initComponents();
        client = s;
        lbNama.setText(nama);
        lbAlamat.setText(alamat);
        lbKota.setText(kota);
        lbHarga.setText(harga);
        lbTipe.setText(tipe);
        inp = inps;
        out = outs; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNama = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtTipe = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        lbTipe = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        txtKota = new javax.swing.JLabel();
        lbKota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNama.setFont(new java.awt.Font("SF UI Text", 1, 24)); // NOI18N
        lbNama.setForeground(new java.awt.Color(0, 51, 102));
        lbNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNama.setText("Nama Properti");

        txtAlamat.setFont(new java.awt.Font("SF UI Text", 1, 16)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(0, 51, 102));
        txtAlamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlamat.setText("Alamat");

        txtHarga.setFont(new java.awt.Font("SF UI Text", 1, 16)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(0, 51, 102));
        txtHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHarga.setText("Harga");

        txtTipe.setFont(new java.awt.Font("SF UI Text", 1, 16)); // NOI18N
        txtTipe.setForeground(new java.awt.Color(0, 51, 102));
        txtTipe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipe.setText("Tipe Properti");

        lbHarga.setFont(new java.awt.Font("SF UI Text", 0, 20)); // NOI18N
        lbHarga.setForeground(new java.awt.Color(0, 51, 102));
        lbHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHarga.setText("Harga");

        lbTipe.setFont(new java.awt.Font("SF UI Text", 0, 16)); // NOI18N
        lbTipe.setForeground(new java.awt.Color(0, 51, 102));
        lbTipe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTipe.setText("Tipe Properti");

        lbAlamat.setFont(new java.awt.Font("SF UI Text", 0, 16)); // NOI18N
        lbAlamat.setForeground(new java.awt.Color(0, 51, 102));
        lbAlamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAlamat.setText("Alamat");

        txtKota.setFont(new java.awt.Font("SF UI Text", 1, 16)); // NOI18N
        txtKota.setForeground(new java.awt.Color(0, 51, 102));
        txtKota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKota.setText("Kota");

        lbKota.setFont(new java.awt.Font("SF UI Text", 0, 16)); // NOI18N
        lbKota.setForeground(new java.awt.Color(0, 51, 102));
        lbKota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKota.setText("Kota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKota, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTipe, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                        .addComponent(txtAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbNama)
                .addGap(26, 26, 26)
                .addComponent(txtTipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAlamat)
                .addGap(24, 24, 24)
                .addComponent(txtKota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbKota)
                .addGap(18, 18, 18)
                .addComponent(txtHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetailProperti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetailProperti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetailProperti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetailProperti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetailProperti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbKota;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbTipe;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtKota;
    private javax.swing.JLabel txtTipe;
    // End of variables declaration//GEN-END:variables
}
