 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaAppServer;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author Acer
 */
public class FormChatUser extends javax.swing.JFrame implements Runnable{
    Socket client;
    String pesan="";
    DataOutputStream out;
    BufferedReader inp;
    Thread t; 
    String nama ="";
    String userid = "";
    /**
     * Creates new form FormChatUser
     */
    public FormChatUser() {
//        try {
//            initComponents();
//            
//            ss = new ServerSocket(34123);
//            client = ss.accept();
//            nama = "budi";
//            
//            this.out = new DataOutputStream(client.getOutputStream());
//            this.inp = new BufferedReader(new InputStreamReader(client.getInputStream()));
//            
//            if(t == null)
//            {
//                this.t = new Thread(this,"Client");
//
//                t.start();
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(FormChatUser.class.getName()).log(Level.SEVERE, null, ex);
//        }
   }
    
    public FormChatUser(Socket s, String nama_user, String user_id, 
            String pemilik, BufferedReader inps, DataOutputStream outs) {
       
         try {
             initComponents();
            
            client = s;  
            nama = pemilik; 
            userid = user_id; 
            jLabel1.setText(nama_user);
            inp = inps;
            out = outs;
           // this.out = new DataOutputStream(client.getOutputStream());
       //     this.inp = new BufferedReader(new InputStreamReader(client.getInputStream()));
            
            if(t == null)
            {
                this.t = new Thread(this,"Client");

                t.start();
            }
          
        } catch (Exception ex) {
            Logger.getLogger(FormChatUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void sendChat(String msg){
        try {
            if(msg.contains("keluar")){
                this.dispose();
            }
             //this.out = new DataOutputStream(client.getOutputStream());
         
            out.writeBytes(msg+"\n");
        } catch (Exception ex) {
            Logger.getLogger(FormChatUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     private void showChat(){
        try 
        {
          //  this.inp = new BufferedReader(new InputStreamReader(client.getInputStream()));
            String pesan= inp.readLine();
            if(pesan.contains("keluar")){
                this.dispose();
            }
            
            else if(!(pesan.contains("chat"))){
               if(!(pesan.contains(jLabel1.getText() +":"))){
                   pesan = jLabel1.getText() + pesan;
               }
                
                txtAreaMsg.append(pesan +"\n");
               
                DateFormat date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Calendar cal = Calendar.getInstance();
                String waktu = date.format(cal.getTime());

                UserServer s = new UserServer(userid);
                chat c = new chat(s,waktu,pesan);
                c.CatatChat();
               
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(FormChatUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMsg = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSend1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaMsg.setColumns(20);
        txtAreaMsg.setRows(5);
        jScrollPane1.setViewportView(txtAreaMsg);

        txtMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMsgMousePressed(evt);
            }
        });

        jLabel2.setText("Pesan:");

        btnSend.setText("Kirim");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("kennethangelo");

        btnSend1.setText("Audio");
        btnSend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSend1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSend1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSend))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String pesan = txtMsg.getText();
        this.sendChat(nama+": "+pesan);
        txtAreaMsg.append("Me: "+ pesan +"\n");
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSend1ActionPerformed
        FormAudioServer frm = new FormAudioServer();
        frm.setVisible(true);
        
    }//GEN-LAST:event_btnSend1ActionPerformed

    private void txtMsgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMsgMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChatUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSend1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaMsg;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
           
            String join = "chat-" + jLabel1.getText()+ "-"+nama ;
            
            this.sendChat(join);
            
            while (true) 
            {
                this.showChat();
                
            }
        } catch (Exception e) {
             Logger.getLogger(FormChatUser.class.getName()).log(Level.SEVERE, null, e);
        }//To change body of generated methods, choose Tools | Templates.
    }
}
